### ISSUE TITLE
Multi-site Live Preview - Unable to verify your data submission

### ISSUE THREAD

**Issue by richhayler** [verbb/knock-knock#21]
### Description
When attempting to live preview a site in a multisite setup that has knock knock enabled, I'm encountering the error message "Unable to verify your data submission" upon entering and submitting the knock knock password.

While it would be great to have this issue resolved, It may be an improvement to the plugin to simply disable knock knock for live preview requests?

### Additional info
- Plugin version:
- Craft version: 3.4.11

**Comment by engram-design** [comment]
Yep, just going to disable it for Live Preview, in [1.2.3](https://github.com/verbb/knock-knock/releases/tag/1.2.3)

**Comment by richhayler** [comment]
Hey Josh,

I've just updated to the latest release but I'm still getting the "site locked" prompt to enter a password when viewing a site in live preview. I've cleared caches and toggled knock knock settings. I've tried both enabling for all sites (default) and unchecking that option and toggling for a specific site.

From what I can see it might be disabled in live preview if viewing an entry from the same site as logged in via the control panel but if viewing a page from a different site (than logged in via the control panel) I believe it's this scenario where it is prompting for the password.

I'm happy to test any updates if you need me to :)

**Comment by engram-design** [comment]
Sounds like you might've been using two different domains for the sites, so there's a cross-domain thing going on? If so, I've just tagged [1.2.4](https://github.com/verbb/knock-knock/releases/tag/1.2.4) which should help against this.

**Comment by richhayler** [comment]
Yes that's right. I've updated to 1.2.4 and 1.2.4.1 but unfortunately I'm still getting prompted with the knock knock password input. This is happening when logged into the CP for site-a.com and previewing an entry in site-b.com.

**Comment by engram-design** [comment]
Strange, that's exactly what I tested locally. Maybe we can setup a remote session or something over Discord?

**Comment by richhayler** [comment]
Happy to this evening if you have the time. I’m free from 730pm onwards.

**Comment by richhayler** [comment]
I've taken another look and interestingly while I'm still seeing the same issue I described, if I change any content for the entry while in live preview the preview window updates and displays the entry without prompting for the knock knock password. It seems it might just prompt for the password when initialising live preview and not editing any content.

**Comment by engram-design** [comment]
Aha, good pickup here - hopefully _finally_ fixed now in [1.2.4.2](https://github.com/verbb/knock-knock/releases/tag/1.2.4.2)!

**Comment by richhayler** [comment]
Updated to 1.2.4.2 but unfortunately still the same behaviour as described when initially previewing the entry.

**Comment by richhayler** [comment]
It's working for me now - thanks Josh!
